Don't fail on CI where there are no slow tests in the changed files (#47)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -42,5 +42,7 @@ jobs:
         with:
           PATTERNS: test/**/*_test.exs
       - name: Changed slow tests
-        run: mix test --only slow ${{ env.GIT_DIFF_FILTERED }}
+        # mix test exits with a non-zero code if there are no matching tests,
+        # so we make sure we fail only when the test suite fails
+        run: mix test test/bumblebee_test.exs --only slow --exit-status 100 ${{ env.GIT_DIFF_FILTERED }} || [ $? -ne 100 ]
         if: ${{ env.GIT_DIFF_FILTERED != '' }}
